src/LineList.Cenovus.Com.UI.New/Controllers/InsulationDefaultController.cs
using AutoMapper;
using LineList.Cenovus.Com.API.DataTransferObjects.EpProjectInsulationDefault;
using LineList.Cenovus.Com.API.DataTransferObjects.EpProjectInsulationDefaultColumn;
using LineList.Cenovus.Com.API.DataTransferObjects.EpProjectInsulationDefaultRow;
using LineList.Cenovus.Com.API.DataTransferObjects.InsulationDefault;
using LineList.Cenovus.Com.API.DataTransferObjects.InsulationDefaultColumn;
using LineList.Cenovus.Com.API.DataTransferObjects.InsulationDefaultDetail;
using LineList.Cenovus.Com.API.DataTransferObjects.InsulationDefaultRow;
using LineList.Cenovus.Com.Domain.DataTransferObjects;
using LineList.Cenovus.Com.Domain.Interfaces.ServiceInterfaces;
using LineList.Cenovus.Com.Domain.Models;
using LineList.Cenovus.Com.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LineList.Cenovus.Com.UI.Controllers
{
    [Authorize(Policy = "Admin")]
    public class InsulationDefaultController : Controller
    {
        private readonly IInsulationDefaultService _insulationDefaultService;
        private readonly IMapper _mapper;
        private readonly CurrentUser _currentUser;

        private readonly IInsulationMaterialService _insulationMaterialService;
        private readonly IInsulationTypeService _insulationTypeService;
        private readonly ITracingTypeService _tracingTypeService;
        private readonly IInsulationThicknessService _insulationThicknessService;
        private readonly IInsulationDefaultDetailService _insulationDefaultDetailService;
        private readonly IInsulationDefaultRowService _insulationDefaultRowService;
        private readonly IInsulationDefaultColumnService _insulationDefaultColumnService;
        private readonly ISpecificationService _specificationService;

        private readonly IEpProjectInsulationDefaultService _epProjectInsulationDefaultService;
        private readonly IEpProjectInsulationDefaultDetailService _epProjectInsulationDefaultDetailService;
        private readonly IEpProjectInsulationDefaultColumnService _epProjectInsulationDefaultColumnService;
        private readonly IEpProjectInsulationDefaultRowService _epProjectInsulationDefaultRowService;

        public InsulationDefaultController(IInsulationDefaultService insulationDefaultService,
            IMapper mapper,
            IInsulationMaterialService insulationMaterialService,
            IInsulationTypeService insulationTypeService,
            ITracingTypeService tracingTypeService,
            IInsulationThicknessService insulationThicknessService,
            IInsulationDefaultRowService insulationDefaultRowService,
            IInsulationDefaultColumnService insulationDefaultColumnService,
            IInsulationDefaultDetailService insulationDefaultDetailService,
            ISpecificationService specificationService,
            IEpProjectInsulationDefaultService epProjectInsulationDefaultService,
            IEpProjectInsulationDefaultDetailService epProjectInsulationDefaultDetailService,
            IEpProjectInsulationDefaultColumnService epProjectInsulationDefaultColumnService,
            IEpProjectInsulationDefaultRowService epProjectInsulationDefaultRowService,
            CurrentUser currentUser
            )
        {
            _insulationDefaultService = insulationDefaultService;
            _mapper = mapper;
            _insulationMaterialService = insulationMaterialService;
            _insulationTypeService = insulationTypeService;
            _tracingTypeService = tracingTypeService;
            _insulationThicknessService = insulationThicknessService;
            _insulationDefaultColumnService = insulationDefaultColumnService;
            _insulationDefaultRowService = insulationDefaultRowService;
            _insulationDefaultDetailService = insulationDefaultDetailService;
            _specificationService = specificationService;
            _epProjectInsulationDefaultService = epProjectInsulationDefaultService;
            _epProjectInsulationDefaultDetailService = epProjectInsulationDefaultDetailService;
            _epProjectInsulationDefaultColumnService = epProjectInsulationDefaultColumnService;
            _epProjectInsulationDefaultRowService = epProjectInsulationDefaultRowService;
            _currentUser = currentUser;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var insulationDefaults = await _insulationDefaultService.GetAll();
            var insulationDefaultDtos = _mapper.Map<IEnumerable<InsulationDefaultResultDto>>(insulationDefaults);
            return View(insulationDefaultDtos);
        }

        [HttpGet]
        public async Task<JsonResult> InsulationDefaultFeed()
        {
            var insulationDefaults = await _insulationDefaultService.GetAll();
            var insulationDefaultDtos = _mapper.Map<IEnumerable<InsulationDefaultResultDto>>(insulationDefaults);
            return Json(new { data = insulationDefaultDtos });
        }

        [HttpGet]
        public async Task<IActionResult> GetDetails(Guid id, string type = "D")
        {
            var insulationDefault = await _insulationDefaultService.GetById(id);
            if (insulationDefault == null)
            {
                return NotFound();
            }

            var rows = await _insulationDefaultRowService.GetByInsulationDefaultId(id);
            var columns = await _insulationDefaultColumnService.GetByInsulationDefaultId(id);

            var viewModel = new InsulationDefaultDetailsViewModel
            {
                InsulationDefault = _mapper.Map<InsulationDefaultResultDto>(insulationDefault),
                InsulationDefaultRows = _mapper.Map<IEnumerable<InsulationDefaultRowResultDto>>(rows),
                InsulationDefaultColumns = _mapper.Map<IEnumerable<InsulationDefaultColumnResultDto>>(columns).OrderBy(c => c.MinOperatingTemperature)
            };

            var detailDtos = new List<InsulationDefaultDetailResultDto>();
            foreach (var r in rows)
            {
                foreach (var c in columns)
                {
                    var cellDetails = await _insulationDefaultDetailService
                        .GetByInsulationDefaultId(r.Id, c.Id);
                    detailDtos.AddRange(
                        _mapper.Map<IEnumerable<InsulationDefaultDetailResultDto>>(cellDetails)
                    );
                }
            }
            viewModel.InsulationDefaultDetails = detailDtos;
            if (type == "D")
            {
                viewModel.GridData = await GetInsulationDefaultGrid(id);
            }
            return PartialView("_InsulationDefaultDetails", viewModel);
            //var insulationDefault = await _insulationDefaultService.GetById(id); // Fetch insulation details
            ////var defaultRow = await _insulationDefaultRowService.GetAll();
            ////var defaultDetail = await _insulationDefaultDetailService.GetAll();
            ////var insulationThicknesses = await _insulationThicknessService.GetAll();

            //var insulationDefaultRows = await _insulationDefaultRowService.GetByInsulationDefaultId(id);
            //var insulationDefaultColumns = await _insulationDefaultColumnService.GetByInsulationDefaultId(id);
            //var insulationDefaultDetails = await _insulationDefaultDetailService.GetAll();


            ////var insulationThicknesses = await _insulationThicknessService.GetById(id); // Fetch related thicknesses

            //InsulationDefaultDetailsViewModel insulationDefaultDetailsViewModel = new InsulationDefaultDetailsViewModel();
            //insulationDefaultDetailsViewModel.InsulationDefault = _mapper.Map<InsulationDefaultResultDto>(insulationDefault);

            //if (type == "D")
            //{
            //    //var insulationDefaultRows = await _epProjectInsulationDefaultRowService.GetByInsulationDefaultId(id);
            //    //var insulationDefaultColumns = await _epProjectInsulationDefaultColumnService.GetByInsulationDefaultId(id);

            //    //var insulationDefaultRows = await _insulationDefaultRowService.GetByInsulationDefaultId(id);
            //    //var insulationDefaultColumns = await _insulationDefaultColumnService.GetByInsulationDefaultId(id);
            //    insulationDefaultDetailsViewModel.InsulationDefaultRows = _mapper.Map<IEnumerable<InsulationDefaultRowResultDto>>(insulationDefaultRows);
            //    insulationDefaultDetailsViewModel.InsulationDefaultColumns = _mapper.Map<IEnumerable<InsulationDefaultColumnResultDto>>(insulationDefaultColumns).OrderBy(m => m.MinOperatingTemperature);
            //    insulationDefaultDetailsViewModel.GridData = await GetInsulationDefaultGrid(id);
            //    insulationDefaultDetailsViewModel.InsulationDefault = _mapper.Map<InsulationDefaultResultDto>(insulationDefault);
            //}

            //if (insulationDefault == null)
            //{
            //    return NotFound();
            //}

            //return PartialView("_InsulationDefaultDetails", insulationDefaultDetailsViewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetDetailsEp(Guid id, string type = "D")
        {
            var insulationDefault = await _epProjectInsulationDefaultService.GetById(id); // Fetch insulation details
            var insulationThicknesses = await _insulationThicknessService.GetById(id); // Fetch related thicknesses

            EpProjectInsulationDefaultDetailsViewModel insulationDefaultDetailsViewModel = new EpProjectInsulationDefaultDetailsViewModel();
            insulationDefaultDetailsViewModel.InsulationDefault = _mapper.Map<EpProjectInsulationDefaultResultDto>(insulationDefault);

            if (type == "D")
            {
                var insulationDefaultRows = await _epProjectInsulationDefaultRowService.GetByInsulationDefaultId(id);

src/LineList.Cenovus.Com.UI.New/Controllers/InsulationDefaultDetailsController.cs
using AutoMapper;
using LineList.Cenovus.Com.API.DataTransferObjects.InsulationDefaultDetail;
using LineList.Cenovus.Com.Domain.DataTransferObjects;
using LineList.Cenovus.Com.Domain.Interfaces.ServiceInterfaces;
using LineList.Cenovus.Com.Domain.Models;
using LineList.Cenovus.Com.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LineList.Cenovus.Com.UI.New.Controllers
{
    [Authorize(Policy = "Admin")]
    public class InsulationDefaultDetailsController : Controller
    {
        private readonly IInsulationDefaultDetailService _insulationDefaultDetailService;
        private readonly IInsulationDefaultRowService _insulationDefaultRowService;
        private readonly IInsulationDefaultColumnService _insulationDefaultColumnService;
        private readonly ISizeNpsService _sizeNpsService;
        private readonly IInsulationThicknessService _insulationThicknessService;
        private readonly IMapper _mapper;
        private readonly CurrentUser _currentUser;

        public InsulationDefaultDetailsController(IInsulationDefaultDetailService insulationDefaultDetailService,
            IInsulationDefaultRowService insulationDefaultRowService,
            IInsulationDefaultColumnService insulationDefaultColumnService,
            ISizeNpsService sizeNpsService,
            IInsulationThicknessService insulationThicknessService,
            IMapper mapper, CurrentUser currentUser)
        {
            _insulationDefaultDetailService = insulationDefaultDetailService;
            _insulationDefaultRowService = insulationDefaultRowService;
            _insulationDefaultColumnService = insulationDefaultColumnService;
            _sizeNpsService = sizeNpsService;
            _insulationThicknessService = insulationThicknessService;
            _mapper = mapper;
            _currentUser = currentUser;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id, Guid insulationDefaultId, Guid rowId, Guid columnId)
        {
            var insulationDefaultDetail = await _insulationDefaultDetailService.GetById(id);
            InsulationDefaultRow row = null;
            InsulationDefaultColumn col = null;
            if (insulationDefaultDetail == null)
            {
                row = await _insulationDefaultRowService.GetById(rowId);
                col = await _insulationDefaultColumnService.GetById(columnId);
            }
            else
            {
                row = await _insulationDefaultRowService.GetById(insulationDefaultDetail.InsulationDefaultRowId);
                col = await _insulationDefaultColumnService.GetById(insulationDefaultDetail.InsulationDefaultColumnId);
            }
            var sizeNPS_s = _sizeNpsService.GetAll().Result.Where(s => s.Id == row.SizeNpsId || s.IsActive == true).OrderBy(s => s.SortOrder).ToList();
            var insulationThicknesses = _insulationThicknessService.GetAll().Result.Where(s => s.IsActive == true).OrderBy(s => s.SortOrder).ToList();
            var tracingType = col.InsulationDefault.TracingType != null ? col.InsulationDefault.TracingType.Name : string.Empty;
            InsulationDefaultDetailsEditViewModel model = new InsulationDefaultDetailsEditViewModel()
            {
                Id = id,
                MinOperatingTemperature = col.MinOperatingTemperature.HasValue ? col.MinOperatingTemperature.Value.ToString() : string.Empty,
                MaxOperatingTemperature = col.MaxOperatingTemperature.HasValue ? col.MaxOperatingTemperature.Value.ToString() : string.Empty,
                SizeNpsId = row.SizeNpsId,
                InsulationDefaultRowId = row.Id,
                InsulationDefaultColumnId = col.Id,
                TracingType = tracingType,
                SizeNps_s = sizeNPS_s,
                insulationThicknesses = insulationThicknesses
            };
            if (insulationDefaultDetail != null)
            {
                model.CreatedBy = insulationDefaultDetail.CreatedBy;
                model.CreatedOn = insulationDefaultDetail.CreatedOn;
                model.ModifiedBy = insulationDefaultDetail.ModifiedBy;
                model.ModifiedOn = insulationDefaultDetail.ModifiedOn;
                model.InsulationThicknessId = insulationDefaultDetail.InsulationThicknessId;
            }

            return PartialView("_Update", model);
        }

        [HttpPost]
        public async Task<JsonResult> Update(InsulationDefaultDetailEditDto model)
        {
            InsulationDefaultDetail insulationDefaultDetail = null;
            if (model.Id == Guid.Empty)
            {
                insulationDefaultDetail = new InsulationDefaultDetail()
                {
                    Id = Guid.NewGuid(),
                    CreatedBy = _currentUser.FullName,
                    CreatedOn = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time")),
                    ModifiedBy = _currentUser.FullName,
                    ModifiedOn = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time")),
                    InsulationDefaultColumnId = model.InsulationDefaultColumnId,
                    InsulationDefaultRowId = model.InsulationDefaultRowId
                };
                await _insulationDefaultDetailService.Add(insulationDefaultDetail);
            }
            else
                insulationDefaultDetail = await _insulationDefaultDetailService.GetById(model.Id);
            insulationDefaultDetail.InsulationThicknessId = model.InsulationThicknessId;
            insulationDefaultDetail.ModifiedBy = _currentUser.FullName;
            insulationDefaultDetail.ModifiedOn = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time"));
            var updatedInsulationDefaultDetail = await _insulationDefaultDetailService.Update(insulationDefaultDetail);

            if (updatedInsulationDefaultDetail == null)
                return Json(new { success = false, ErrorMessage = "<b>Duplicate Name</b> : The value entered in name field already exists!" });

            return Json(new { success = true });
        }

        [HttpDelete]
        public async Task<JsonResult> Delete(Guid id)
        {
            var insulationDefaultDetail = await _insulationDefaultDetailService.GetById(id);
            if (insulationDefaultDetail == null)
                return Json(new { success = false, ErrorMessage = "Insulation Default Detail not found" });

            await _insulationDefaultDetailService.Remove(insulationDefaultDetail);

            return Json(new { success = true });
        }


    }
}

src/LineList.Cenovus.Com.UI.New/Views/InsulationDefault/_InsulationDefaultDetails.cshtml
@using LineList.Cenovus.Com.Domain.DataTransferObjects
@model InsulationDefaultDetailsViewModel
<div id="mainPopup">
    <dl class="row">
        <dt class="col-sm-4">Name:</dt>
        <dd class="col-sm-8"> @($"{Model.InsulationDefault.Name} - {Model.InsulationDefault.Description}")</dd>


        <dt class="col-sm-4">Insulation Material:</dt>
        <dd class="col-sm-8"> @($"{Model.InsulationDefault.InsulationMaterialName} - {Model.InsulationDefault.InsulationMaterialDescription}")</dd>

        <dt class="col-sm-4">Insulation Type:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.InsulationTypeName} - {Model.InsulationDefault.InsulationTypeDescription}")</dd>

        <dt class="col-sm-4">Tracing Type:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.TracingTypeName} - {Model.InsulationDefault.TracingTypeDescription}")</dd>
    </dl>
    <div>
        <button type="button" class="btn btn-primary" data-id="@Model.InsulationDefault.Id" id="btnEditColumn">Edit Column Definition</button>
        <button type="button" class="btn btn-primary" data-id="@Model.InsulationDefault.Id" id="btnEditRow">Edit Row Definition</button>
    </div>
     @if (!Model.GridData.Any())
  {
    <div class="alert alert-info mt-3">
      No thickness/tracer definitions have been set up yet.
    </div>
  }
  else
  {
    <h5 class="mt-3">Insulation Thickness and Number of Tracers can be edited by clicking on their value in the table below</h5>
    <div class="table" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-bordered">
            <thead class="sticky-table-header">
                <tr>
                        <th rowspan="3" class="align-middle text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Size NPS</th>
                        <th colspan="@(Model.GridData.First().Columns.Count() * 2)" class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Operating Temperature</th>
                </tr>
                <tr>
                    @if (Model.GridData.Any())
                    {
                        @foreach (var col in Model.GridData.First().Columns)
                        {
                                <th colspan="2" class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">@col.TemperatureRange</th>
                        }
                    }
                </tr>
                <tr>
                    @if (Model.GridData.Any())
                    {
                        @foreach (var col in Model.GridData.First().Columns)
                        {
                                <th style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Ins Thk</th>
                                <th style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">No. Tracers</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in Model.GridData)
                {
                    <tr>
                        <td>@row.Nps</td>
                        @foreach (var col in row.Columns)
                        {
                            <td>
                                    <a href="#" class="open-modal" data-id="@col.ColumnId" data-url="@Url.Action("Update", "InsulationDefaultDetails")?@col.DetailsUrl">
                                    @col.InsulationThickness
                                </a>
                            </td>
                            <td>
                                    <a href="#" class="open-modal" data-id="@col.ColumnId" data-url="@Url.Action("Update", "InsulationDefaultDetails")?@col.DetailsUrl">
                                    @col.NumberOfTracers
                                </a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
    }
</div>

<div id="dynamicContent"></div>

src/LineList.Cenovus.Com.UI.New/Views/InsulationDefault/_InsulationDefaultDetailsEp.cshtml
@using LineList.Cenovus.Com.Domain.DataTransferObjects
@model EpProjectInsulationDefaultDetailsViewModel

<style>
    table.table-bordered {
        border-collapse: collapse;
    }

        table.table-bordered th,
        table.table-bordered td {
            border: 1px solid #dee2e6 !important;
        }

    thead.sticky-table-header th {
        background-color: #1e4854;
        color: white;
        border: 1px solid #dee2e6 !important;
        text-align: center;
        vertical-align: middle;
    }
</style>

<div id="mainPopup">
    <dl class="row">
        <dt class="col-sm-4">Name:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.Name} - {Model.InsulationDefault.Description}")</dd>

        <dt class="col-sm-4">Insulation Material:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.InsulationMaterialName} - {Model.InsulationDefault.InsulationMaterialDescription}")</dd>

        <dt class="col-sm-4">Insulation Type:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.InsulationTypeName} - {Model.InsulationDefault.InsulationTypeDescription}")</dd>

        <dt class="col-sm-4">Tracing Type:</dt>
        <dd class="col-sm-8">@($"{Model.InsulationDefault.TracingTypeName} - {Model.InsulationDefault.TracingTypeDescription}")</dd>
    </dl>

    <div>
        <button type="button" class="btn btn-primary" data-id="@Model.InsulationDefault.Id" id="btnEditColumn" data-id="@Model.InsulationDefault.Id"
                data-name="@Model.InsulationDefault.Name"
                data-desc="@Model.InsulationDefault.Description">
            Edit Column Definition
        </button>
        <button type="button" class="btn btn-primary" data-id="@Model.InsulationDefault.Id" id="btnEditRow">Edit Row Definition</button>
    </div>

    <h5 class="mt-3">Insulation Thickness and Number of Tracers can be edited by clicking on their value in the table below</h5>
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-bordered">
            <thead class="sticky-table-header">
                <tr>
                    <th rowspan="3" class="align-middle text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Size NPS</th>
                    <th colspan="@(Model.GridData.First().Columns.Count() * 2)" class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Operating Temperature</th>
                </tr>
                <tr>
                    @foreach (var col in Model.GridData.First().Columns)
                    {
                        <th colspan="2" class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">@col.TemperatureRange</th>
                    }
                </tr>
                <tr>
                    @foreach (var col in Model.GridData.First().Columns)
                    {
                        <th class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">Ins Thk</th>
                        <th class="text-center" style="border: 1px solid #dee2e6; padding-bottom: 3px;padding-top: 3px;">No. Tracers</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var row in Model.GridData)
                {
                    <tr>
                        <td>@row.Nps</td>
                        @foreach (var col in row.Columns)
                        {
                            <td>
                                <a href="#" class="open-modal" data-id="@col.ColumnId" data-url="@Url.Action("Update", "EpProjectInsulationDefaultDetails")?@col.DetailsUrl">
                                    @col.InsulationThickness
                                </a>
                            </td>
                            <td>
                                <a href="#" class="open-modal" data-id="@col.ColumnId" data-url="@Url.Action("Update", "EpProjectInsulationDefaultDetails")?@col.DetailsUrl">
                                    @col.NumberOfTracers
                                </a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="dynamicContent"></div>